module.exports = {
  apps: [
    {
      name: "abmmcn-backend",
      script: "server.js",
      cwd: "./backend",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        DB_SERVER: "mcn-bidb-svr",
        DB_PORT: 1433,
        DB_USER: "app_user",
        DB_PASSWORD: "Pd6EdwB%ta",
        DB_DATABASE: "APPDATA",
        TRIAL_DB: "BI_EDITOR",
        TRIAL_TABLE: "TEST_ABM",
        CORS_ORIGIN: "*",
        JWT_SECRET: "your-super-secret-jwt-key-here",
        JWT_EXPIRES_IN: "24h",
        LOG_LEVEL: "info",
        CURRENT_IP: "192.168.1.31:3001",
      },
      error_file: "../logs/backend-error.log",
      out_file: "../logs/backend-out.log",
      log_file: "../logs/backend-combined.log",
      time: true,
    },
    {
      name: "abmmcn-frontend",
      script: "serve",
      args: "-s dist -l 5173 --host 0.0.0.0",
      cwd: "./frontend",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        PORT: 5173,
        CURRENT_IP: "192.168.1.31:3001",
      },
      error_file: "../logs/frontend-error.log",
      out_file: "../logs/frontend-out.log",
      log_file: "../logs/frontend-combined.log",
      time: true,
    },
  ],
};
